/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

### MAGNITUDE ANALYSIS
-- -->> MAGNITUDE means, Compare the measure values by categories.
-- > it help us understand the importance of different categories
-- > formula :    [measure] by [Dimension]
-- 	eg, Total Sales By Country ,Total Quantity by Category , Average Price by Product , Total Orders By Customer



-- > Find Total Customers by Countries
SELECT COUNT(customer_key) AS total_customers,country
FROM gold_dim_customers 
GROUP BY country
ORDER BY COUNT(customer_key) DESC;

-- > Find Total customers by Gender
SELECT gender,
	COUNT(customer_key) as TOTAL_CUSTOMERS
FROM gold_dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC;

-- > Find Total Products by category
SELECT category,
	COUNT(product_key) AS TOTAL_PRODUCTS_BY_CATEGORY
FROM gold_dim_products
GROUP BY category
ORDER BY COUNT(product_key) DESC;

-- > What is the average costs in each category ? 
SELECT category,
	AVG(cost) AS AVERAGE_COST
FROM gold_dim_products
GROUP BY category
ORDER BY AVG(cost) DESC;

-- > What is the Total Revenue generated for each category ? 
SELECT p.category,sum(s.sales_amount) as total_revenue
FROM gold_fact_sales s
LEFT JOIN gold_dim_products p 
ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- > Find Total Revenue is generated by each customer
SELECT c.customer_key,c.first_name,c.last_name,
	SUM(s.sales_amount) as TOTAL_REVENUE
FROM gold_fact_sales s
LEFT JOIN gold_dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY TOTAL_REVENUE DESC;

-- > What is the distrubution of sold items across countries? 
SELECT c.country,
	SUM(quantity) as TOTAL_DISTRIBUTION
FROM gold_fact_sales s
LEFT JOIN gold_dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY TOTAL_DISTRIBUTION DESC;